on: push
name: Install and Test
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: nuxt/actions-yarn@node-10
        with:
          args: install
      - name: Test
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: test
