version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    ignored_updates:
      - match:
          dependency_name: metro-react-native-babel-preset
      - match:
          dependency_name: metro
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
          dependency_name: "@types/*"
      - match:
          dependency_name: aws-sdk
      - match:
          dependency_name: stripe
      - match:
          dependency_name: tics
      - match:
          dependency_name: semver
      - match:
          dependency_name: ava
      - match:
          dependency_name: polished
      - match:
          dependency_name: prettier
      - match:
          dependency_name: "@jonny/eslint-config"
      - match:
          dependency_name: ts-node
      - match:
          dependency_name: mongodb-memory-server
      - match:
          dependency_name: "@react-navigation/bottom-tabs"
      - match:
          dependency_name: "@react-navigation/native"
      - match:
          dependency_name: "@react-navigation/stack"
      - match:
          dependency_name: react-native-device-info
      - match:
          dependency_name: react-native-redash
      - match:
          dependency_name: typescript
      - match:
          dependency_name: date-fns
      - match:
          dependency_name: ts-unused-exports
      - match:
          dependency_name: ts-loader
      - match:
          dependency_name: react-native-screens
      - match:
          dependency_name: "@react-native-community/async-storage"
      - match:
          dependency_name: pg
      - match:
          dependency_name: webpack-dev-middleware
      - match:
          dependency_name: ts-jest
      - match:
          dependency_name: jest
      - match:
          dependency_name: react-native-safe-area-context
    version_requirement_updates: increase_versions
