on: push
name: Install and Test
jobs:
  install:
    name: Install
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn test
      - name: Magic
        uses: JonnyBurger/10x-actions@master
        with:
          pod-dir: ios
          github-token: "${{ secrets.GITHUB_TOKEN }}"
